pub mod activity_panel;
pub mod cc_widgets;
pub mod command_palette;
pub mod components;
pub mod diff;
pub mod double_shift;
pub mod fuzzy;
pub mod help_modal;
pub mod key_bindings;
pub mod main_view;
pub mod search_overlay;
pub mod session_switcher;
pub mod settings;
pub mod settings_modal;
pub mod sidebar;
mod sidebar_items;
#[cfg(test)]
mod terminal_bench;
pub mod terminal_element;
pub mod terminal_panel;
pub mod toast;
pub mod url_detector;
pub mod worktree_create_modal;
